export const homeCategory = [
  {id: 1, title: 'Trending'},
  {id: 2, title: 'New'},
  {id: 3, title: 'Movies'},
  {id: 4, title: 'Series'},
  {id: 5, title: 'Animation'},
  {id: 6, title: 'Tv Show'},
  {id: 7, title: 'Action'},
  {id: 8, title: 'Adventure'},
  {id: 9, title: 'Comedy'},
  {id: 10, title: 'Crime'},
];

export const appCategory = [
  {id: 1, title: 'Biographical', number: 932},
  {id: 2, title: 'Western', number: 673},
  {id: 3, title: 'Documentary', number: 126},
  {id: 4, title: 'Action', number: 1096},
  {id: 5, title: 'Fantasy', number: 475},
  {id: 6, title: 'Musical', number: 398},
  {id: 7, title: 'War', number: 56},
  {id: 8, title: 'Independent', number: 49},
  {id: 9, title: 'Crime', number: 399},
  {id: 10, title: 'Sci-fi', number: 821},
  {id: 11, title: 'Comedy', number: 736},
  {id: 12, title: 'Drama', number: 654},
  {id: 13, title: 'Horror', number: 764},
  {id: 14, title: 'Thriller', number: 23},
  {id: 15, title: 'Romance', number: 645},
  {id: 16, title: 'Adventure', number: 987},
  {id: 17, title: 'Animation', number: 547},
  {id: 18, title: 'Family', number: 234},
  {id: 19, title: 'Mystery', number: 645},
  {id: 20, title: 'History', number: 34},
  {id: 21, title: 'Music', number: 764},
  {id: 22, title: 'Sport', number: 34},
  {id: 23, title: 'Costume', number: 243},
  {id: 24, title: 'Reality-TV', number: 543},
  {id: 25, title: 'News', number: 73},
  {id: 26, title: 'Game-Show', number: 143},
  {id: 27, title: 'Short', number: 83},
  {id: 28, title: 'Talk-Show', number: 72},
  {id: 29, title: 'Film-Noir', number: 247},
];
